# Generated by Django 4.1.7 on 2023-04-05 20:55

import alpha.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('average_cost', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('date_released', models.DateField(blank=True)),
                ('timestamp', models.DateField(auto_now=True)),
                ('desc', models.CharField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=alpha.models.filepath)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('product_rating', models.IntegerField()),
                ('review_content', models.CharField(max_length=2000)),
                ('created_on', models.DateField(blank=True)),
                ('timestamp', models.DateField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
