# Generated by Django 4.1.7 on 2023-04-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0002_alter_product_desc_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
