# Generated by Django 4.1.7 on 2023-04-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0003_remove_review_updated_on_alter_review_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.CharField(max_length=50),
        ),
    ]
