# Generated by Django 4.1.7 on 2023-04-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0004_alter_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
