# Generated by Django 4.1.7 on 2023-04-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0005_remove_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
