# Generated by Django 4.1.7 on 2023-04-04 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0006_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
