# Generated by Django 4.1.7 on 2023-04-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_released',
            field=models.DateField(),
        ),
    ]
