# Generated by Django 4.1.7 on 2023-04-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0009_alter_product_date_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_released',
            field=models.DateField(null=True),
        ),
    ]
