# Generated by Django 4.1.7 on 2023-04-05 09:27

import alpha.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0011_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('average_cost', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('date_released', models.DateTimeField()),
                ('desc', models.CharField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=alpha.models.filepath)),
            ],
        ),
    ]
